### PR TITLE
fix: #243

### PR DESCRIPTION
**Pull request by florentleveque**
## What
- tests execution doesn't work #245 

### Fixes bug(s)
- local unit tests execution works properly
- TODO: fix the Github tests execution bug.

### CODE REVIEW

**Review by alexgarel — APPROVED** [review]
Thanks !

**Comment by alexgarel** [comment]
I validated a draft request :-D

**Comment by florentleveque** [comment]
No problem, I fixed the integration test workflow and the local unit tests, but I have always an error for unit tests workflow in github.

**Review by alexgarel — APPROVED** [review]
Cool, thank you !

**Pull request merged**
